# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run Deno lint and test.
# For more information see: https://github.com/denoland/setup-deno

name: Deno

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

permissions:
  contents: read

jobs:
  setup:
    runs-on: ['self-hosted', 'Linux', 'ARM64']
    name: Retrieve repo
    steps:
      - name: Setup repo
        uses: actions/checkout@v3

  build-node:
    needs: setup
    runs-on: ['self-hosted', 'Linux', 'ARM64']
    name: Build with npm
    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.5.0

      - run: npm ci
      - run: npm run build

  build-deno:
    needs: setup
    name: Download deno binary
    steps:
      - run: wget https://github.com/LukeChannings/deno-arm64/releases/download/v1.24.3/deno-linux-arm64.zip
      - run: unzip deno-linux-arm64.zip 

  registry:
    runs-on: ['self-hosted', 'Linux', 'ARM64']
    name: Build and push image to private repo
    needs: [build-node, build-deno]
    steps:
      - run: docker build -t ${{ secrets.PRIV_REPO }}/yor/qat:latest .
      - run: docker push ${{ secrets.PRIV_REPO }}/yor/qat:latest
