# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run Deno lint and test.
# For more information see: https://github.com/denoland/setup-deno

name: Deno

on:
  push:
    branches: ["qwik-revamp"]
  pull_request:
    branches: ["qwik-revamp"]

permissions:
  contents: read

jobs:
  setup:
    runs-on: ["self-hosted", "Linux", "ARM64"]
    name: Retrieve repo
    steps:
      - name: Setup repo
        uses: actions/checkout@v3

  build:
    needs: setup
    runs-on: ["self-hosted", "Linux", "ARM64"]
    name: Build with npm and Download deno binary
    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.5.0

      - run: npm ci
      - run: npm run build

  registry:
    runs-on: ["self-hosted", "Linux", "ARM64"]
    name: Build and push image to private repo
    needs: build
    steps:
      - run: docker build -t ${{ secrets.PRIV_REPO }}/yor/qat:latest .
      - run: docker push ${{ secrets.PRIV_REPO }}/yor/qat:latest

  kubernetes:
    runs-on: ["self-hosted", "Linux", "ARM64"]
    name: Deploy on kubernetes
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Create KubeConfig
      run: |
        mkdir ${HOME}/.kube
        echo "${{ secrets.KUBE_CONFIG }}"" | base64 --decode > ${HOME}/.kube/config
    - name: Deploy finally
      run: kubectl apply -f k8s/
    - name: Clean up
      run: rm -rf ${HOME}/.kube